title: <p align="center"> Shruti Mohanty </p>

logo: "/images/photo.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shruti-mohanty-27b722172/">LinkedIn</a> |
  <a href="https://github.com/shrutimohanty98">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursuing a Master's degree in Electrical and Computer Engineering at the University of California, Los Angeles (UCLA) with a focus on Machine Learning and Data Science. 
  <br><br>
  I am currently working as a Deep Learning Intern at MathWorks. 
  Previously worked as a Software Developer with the R&D Team at Aruba, Hewlett Packard Enterprise.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
# google_analytics: UA-145578661-1 # Google Analytics tracking ID
